config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Resources
  resources :campaigns
  resources :characters

  # Contact Page
  get 'contact', to: 'contact#contact' #redirect
  post 'request_contact', to: 'contact#request_contact'

  # Home page / root where we arrive at
  root 'home#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
    belongs_to :user
    has_many :characters, dependent: :destroy
    has_one_attached :image
    validates :name, presence: true
    validates :name, uniqueness: true
    scope :user_campaigns, ->(user) { where(['user_id = ?', user.id]) }
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :campaign
  has_one_attached :image
  validates :name, :campaign, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :campaigns, dependent: :destroy
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, 
    if: :devise_controller?
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:account_update) { |u| 
        u.permit(:avatar, :email, :password, :password_confirmation,
        :current_password) 
    } 
    end

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /campaigns or /campaigns.json
  def index
    @campaigns = Campaign.user_campaigns(current_user)
  end

  # GET /campaigns/1 or /campaigns/1.json
  def show
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns or /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)
    @campaign.user = current_user

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: t(".camp_create_msg") }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1 or /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to @campaign, notice: t(".camp_update_msg") }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1 or /campaigns/1.json
  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: t(".camp_destroy_msg") }
      format.js { flash[:notice] = t(".camp_destroy_msg")}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def campaign_params
      params.require(:campaign).permit(:name, :desc, :image)
    end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: %i[ show edit update destroy ]
  before_action :set_campaign, only: [:new, :create]

  # GET /characters or /characters.json
  def index
    # @characters = Character.all
    redirect_to campaigns_url
  end

  # GET /characters/1 or /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = @campaign.characters.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters or /characters.json
  def create
    @character = @campaign.characters.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: t(".char_create_msg") }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1 or /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: t(".char_update_msg") }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1 or /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: t(".char_destroy_msg") }
      format.js { flash[:notice] = t(".char_destroy_msg")}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def character_params
      params.require(:character).permit(:campaign_id, :name, :desc, :image)
    end

    def set_campaign
      @campaign = Campaign.find_by(id: params[:campaign_id]) || Campaign.find(character_params[:campaign_id])
    end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def contact
  end

  def request_contact
    name = params[:name]
    email = params[:email]
    telephone = params[:telephone]
    message = params[:message]

    if email.blank?
      flash[:alert] = I18n.t('contact.request_contact.no_email')
    else
      ContactMailer.contact_email(email, name, telephone, message).deliver_now
      flash[:notice] = I18n.t('contact.request_contact.email_sent')
    end


    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/campaigns/_form.html.haml
= form_for @campaign do |f|
  - if @campaign.errors.any?
    #error_explanation
      %h2= "#{pluralize(@campaign.errors.count, "error")} prohibited this campaign from being saved:"
      %ul
        - @campaign.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :desc
    = f.text_area :desc
  .field 
    = f.file_field :image
  .actions.button
    = f.submit t('.camp_save_msg')

app/views/campaigns/destroy.js.erb
$('#campaign_<%= @campaign.id %>').hide();

app/views/campaigns/edit.html.haml
=render 'shared/shared_form', form_title: t('.camp_edit_msg'), form_name: "form", form_links: "shared/edit_links", ls:@campaign, lb: campaigns_path

app/views/campaigns/index.html.haml
.campaigns_wrapper
  .container

    - @campaigns.in_groups_of(6, false).each do |group|
      .row.card_row
        - group.each do |item|
          .col-lg-4.col-md-6.col-sm-6.col-xs-12.card_col
            %span{id: "campaign_#{item.id}"}
              .card_outer
                .card_icons
                  = link_to (edit_campaign_path(item)) do
                    .i_wrap
                      %i.bi.bi-pencil-fill
                  = link_to (item), method: :delete, data: { confirm: t('.camp_destroy_confirm_msg') }, :remote => true do
                    .i_wrap
                      %i.bi.bi-file-earmark-x-fill
                .card
                  = link_to (item) do
                    - if item.image.attached?
                      = image_tag item.image
                      .card_overlay
                    .content
                      %h3= item.name
                      %span= item.desc
    .add_btn_container
      .button
        = link_to t('.camp_new_msg'), new_campaign_path

app/views/campaigns/new.html.haml
=render 'shared/shared_form', form_title: t('.camp_new_msg'), form_name: "form", form_links: "shared/new_links", ls:"", lb: campaigns_path

app/views/campaigns/show.html.haml
.banner_wrapper
  - if @campaign.image.attached?
    = image_tag @campaign.image
  .banner_inner
    %h1= @campaign.name
    .btn_small
      = link_to t('.camp_edit_link'), edit_campaign_path(@campaign)
      \|
      = link_to t('.camp_back_link'), campaigns_path

.container
  .description 
    %p= @campaign.desc

.character_listing_wrapper
  .container

    .add_btn_container 
      .add_btn_row
        .button
          = link_to t('.camp_show_msg'), new_character_path(campaign_id: @campaign)

    - @campaign.characters.in_groups_of(4, false).each do |group|
      .row.card_row
        - group.each do |item|
          .col-lg-3.col-md-6.col-sm-6.col-xs-12
            %span{id: "character_#{item.id}"}
              .card_outer
                .card_icons
                  = link_to (edit_character_path(item)) do
                    .i_wrap
                      %i.bi.bi-pencil-fill
                  = link_to (item), method: :delete, data: { confirm: t('.camp_destroy_confirm_msg') }, :remote => true do
                    .i_wrap
                      %i.bi.bi-file-earmark-x-fill
                .card
                  = link_to (item) do
                    .img_wrapper
                      - if item.image.attached?
                        = image_tag item.image
                    .content
                      %h3= item.name
                      %span= item.desc

app/views/characters/_form.html.haml
= form_for @character do |f|
  - if @character.errors.any?
    #error_explanation
      %h2= "#{pluralize(@character.errors.count, "error")} prohibited this character from being saved:"
      %ul
        - @character.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :campaign
    %p=@character.campaign.name
    = f.hidden_field :campaign_id, value: @character.campaign.id
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :desc
    = f.text_area :desc
  .field 
    = f.file_field :image
  .actions.button
    = f.submit t('.char_save_msg')

app/views/characters/destroy.js.erb
$('#character_<%= @character.id %>').hide();

app/views/characters/edit.html.haml
=render 'shared/shared_form', form_title: t('.char_edit_msg'), form_name: "form", form_links: "shared/edit_links", ls: @character, lb: campaign_path(@character.campaign)

app/views/characters/index.html.haml
%h1 Listing characters

%table
  %thead
    %tr
      %th Campaign
      %th Name
      %th Desc
      %th
      %th
      %th

  %tbody
    - @characters.each do |character|
      %tr
        %td= character.campaign.name
        %td= character.name
        %td= character.desc
        %td= link_to 'Show', character
        %td= link_to 'Edit', edit_character_path(character)
        %td= link_to 'Destroy', character, method: :delete, data: { confirm: t('.char_destroy_confirm_msg') }

%br

= link_to t('.char_new_msg'), new_character_path

app/views/characters/new.html.haml
=render 'shared/shared_form', form_title: t('.char_new_msg'), form_name: "form", form_links: "shared/new_links", ls:"", lb: campaign_path(@character.campaign)

app/views/characters/show.html.haml
.characters_wrapper
  .banner_wrapper
    - if @character.campaign.image.attached?
      = image_tag @character.campaign.image
    .banner_inner
      %h1= @character.campaign.name

  .container
    .description 
      - if @character.image.attached?
        .image_wrapper
          = image_tag @character.image
      %h2= @character.name
      %p= @character.desc

  .add_btn_container 
    .btn_small
      = link_to t('.char_edit_link'), edit_character_path(@character)
      \|
      = link_to t('.char_back_link'), campaign_path(@character.campaign)

app/views/contact/contact.html.haml
.contact_form
    .container
        = form_tag request_contact_path, method: 'post', id: "contact" do
            %h3= t('.title')
            %h4= t('.contact_us')
            = label_tag :name, t('.name')
            = text_field_tag :name, '', title: t('.enter_name'), size: 50
            = label_tag :email, t('.email')
            = email_field_tag :email, '', title: t('.enter_email')
            = label_tag :telephone, t('.telephone')
            = telephone_field_tag :telephone, '', title: t('.enter_telephone')
            = label_tag :message, t('.message')
            = text_field_tag :message, '', title: t('.enter_message'), size: 100
            = submit_tag t('.submit'), class: "submit-btn"

app/views/home/home.html.haml
.home_banner
  %h1= t('.app_banner_title')
  %p= t('.app_banner_desc')

app/views/layouts/application.html.haml
!!!

%html
  %head
    %meta{'charset' => 'utf-8'}
    %meta{'http-equiv' => 'x-ua-compatible', 'content' => 'ie=edge'}

    %title= t('.app_title')

    %meta{'name' => 'description', 'content' => t('app_description')}
    %meta{'name' => 'viewport', 'content' => 'width=device-width, initial-scale=1'}

    %link{:href => "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css", :rel => "stylesheet"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'modernizr'
    = csrf_meta_tags

  %body

    = render 'shared/header'

    .yield_wrapper
      = yield

    = render 'shared/footer'

app/views/shared/_edit_links.html.haml
= link_to 'Show', link_show
\|
= link_to 'Back', link_back

app/views/shared/_footer.html.haml
%footer
    %p &copy; Oliver Krieger

app/views/shared/_header.html.haml
- flash.each do |key, value|
  = content_tag :div, content_tag(:p, value), id: "#{key}" unless value.blank?

%header
  %nav
    %a.burg-menu
      %i
    .container
      .row.header_links
        .col-lg-6.logo
          %img{:alt => "logo", :src => image_url("logo.png")}/
        .col-lg-6
          .links
            %a{:href => "/"}= t('.home_link')
            %a{:href => "/contact"}= t('.contact_link')
            %a{:href => "/campaigns"}= t('.library_link')
            -# %a{:href => ""} characters
            = '|'
            .login_links
              - if user_signed_in?
                -# .username
                -#   %span= "#{current_user.email}"
                - if current_user.avatar.attached?
                  = link_to(edit_user_registration_path, class: "profile") do
                    = image_tag current_user.avatar
                - else
                  .button
                    = link_to t('profile_link'), edit_user_registration_path
                -# .button
                -#   = link_to t('profile'), edit_user_registration_path
                .button
                  = link_to t('log_out_link'), destroy_user_session_path, method: 'delete'
              - else
                .button
                  = link_to t('login_link'), new_user_session_path
                .button
                  = link_to t('sign_up_link'), new_user_registration_path

app/views/shared/_new_links.html.haml
= link_to 'Back', link_back

app/views/shared/_shared_form.html.haml
.form_wrapper
    .form_inner
        %h1= form_title
        = render form_name
        .btn_small
            = render form_links, link_show: ls, link_back: lb
            -# = link_to 'Show', link_show
            -# \|
            -# = link_to 'Back', link_back